name: update_foundation

on:
  schedule:
    - cron: "0 11 * * 1-5"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  FIGMA_FILE_URL: ${{secrets.FIGMA_FILE_URL}}
  FIGMA_TOKEN: ${{secrets.FIGMA_TOKEN}}
  GITHUB_ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up node using nvm
        uses: dcodeIO/setup-node-nvm@master
        with:
          node-version: lts/*

      - name: Update foundation
        run: |
          cd scripts/foundation-gen/

          mkdir jsons

          curl -L https://unpkg.com/@charcoal-ui/theme@3.14.0/src/json/base.json -o jsons/base.json
          curl -L https://unpkg.com/@charcoal-ui/theme@3.14.0/src/json/pixiv-dark.json -o jsons/pixiv-dark.json
          curl -L https://unpkg.com/@charcoal-ui/theme@3.14.0/src/json/pixiv-light.json -o jsons/pixiv-light.json

          npm install
          npm run build
          rm -rf jsons
      - name: Update icon
        run: |
          cd scripts/xcasset-gen

          OUTPUT_ROOT_DIR=icons npx @charcoal-ui/icons-cli@latest figma:export --format pdf

          npm install
          npm run xcasset-gen generate -- --input icons/pdf --output ../../Sources/CharcoalShared/Images.xcassets

          rm -rf icons

      - name: Generate Swift file
        run: |
          swift run --package-path BuildTools swiftgen
          git restore BuildTools/Package.resolved

      - name: Create Pull Request
        run: |
          cd scripts/create-pull-request/
          npm install
          npm run create-pull-request -- --owner="${{github.repository_owner}}" --repo="${GITHUB_REPOSITORY#*/}" --baseBranch="main"
